# https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md

#组件信息
component: scf
name: bilibili_tool

#组件参数配置
inputs:
  name: ${name}_scf
  namespace: default
  enableRoleAuth: false
  src: ./bin/publish/
  handler: index.main_handler
  runtime: CustomRuntime
  region: ap-guangzhou # 函数所在区域，默认广州
  description: This is a function in ${app} application.
  memorySize: 128
  initTimeout: 30
  timeout: 86400
  asyncRunEnable: true
  traceEnable: true
  events: # 根据自己的需要修改
    - timer: # 每日任务触发器
        parameters:
          name: DailyTask
          cronExpression: "0 30 12 * * * *"
          enable: true
          argument: Daily
    - timer: # 天选抽奖触发器
        parameters:
          name: LiveLotteryTask
          cronExpression: "0 0 */4 * * * *"
          enable: true
          argument: LiveLottery
    - timer: # 自动取关
        parameters:
          name: UnfollowBatchedTask
          cronExpression: "0 0 0 * * MON *"
          enable: true
          argument: UnfollowBatched
  environment:
    variables: # 根据自己的需要修改
      Ray_BiliBiliCookies__1: buvid3=2F8EB14B-FC26-4960-8CA8-C19F591F4154143083infoc; rpdid=|(J|)R)|~lum0J'uY|u~)Yu)u; LIVE_BUVID=AUTO9616020755205710; balh_server_inner=__custom__; balh_is_closed=; balh_server_custom_hk=https://bili-proxy.98e.org/; balh_server_custom=https://bili-proxy.98e.org/; blackside_state=1; fingerprint_s=a964176ba210eb52f44646a70b352e17; i-wanna-go-back=-1; _uuid=A9A6DB88-47DC-77BC-F67D-44473CBD8F5200809infoc; buvid4=EE20BB1E-2689-16F6-F519-0570C8CBE51B27839-022012719-xJ7VtYkej0ijrSOmQ5HODg%3D%3D; buvid_fp_plain=undefined; fingerprint3=9a3624e9ca7752c5bf685f72ee9beafe; CURRENT_QUALITY=112; fingerprint=c99948847a2806958f1fd672ba637ed2; CURRENT_BLACKGAP=0; sid=ch4lp0ma; DedeUserID=34404818; DedeUserID__ckMd5=42b3966284c3e53d; SESSDATA=52b3b544%2C1662647177%2C30c81*31; bili_jct=171ad0c68e8795717c5954d91169f9e8; b_ut=5; buvid_fp=c99948847a2806958f1fd672ba637ed2; nostalgia_conf=-1; hit-dyn-v2=1; PVID=1; b_lsid=FAF929CF_180788C3C3C; bp_video_offset_34404818=654772085279686700; innersign=0; CURRENT_FNVAL=80 # cookie，必填
